let button2 = document.querySelector(".main-right-item-list-image2")
let button3 = document.querySelector(".main-right-item-list-image3")
let img = document.querySelector(".main-right-product")
let button1 = document.querySelector(".main-right-item-list-image")
let button4 = document.querySelector(".main-right-item-list-image4")
button2.addEventListener("click", ()=>{
    button1.classList.remove ("active-image")
    button2.classList.add("active-image")
    button3.classList.remove("active-image")
    button4.classList.remove("active-image")
    img.setAttribute("src" , "./image/image-product-2.jpg")
})
button1.addEventListener("click", ()=>{
    button2.classList.remove ("active-image")
    button1.classList.add("active-image")
    button3.classList.remove("active-image")
    button4.classList.remove("active-image")
    img.setAttribute("src" , "./image/image-product-1.jpg")
})
button3.addEventListener("click", ()=>{
    button2.classList.remove ("active-image")
    button1.classList.remove("active-image")
    button3.classList.add("active-image")
    button4.classList.remove("active-image")
    img.setAttribute("src" , "./image/image-product-3.jpg")
})
button4.addEventListener("click", ()=>{
    button2.classList.remove ("active-image")
    button1.classList.remove("active-image")
    button3.classList.remove("active-image")
    button4.classList.add("active-image")
    img.setAttribute("src" , "./image/image-product-4.jpg")
})